version: '2.4'

services:
  myproject:
    build:
      dockerfile: ./Dockerfile
      context: ./
    volumes:
      - "./data/library.db:/data/library.db" # Mount db
      - "/tmp/.X11-unix:/tmp/.X11-unix" # Mount the X11 socket
    environment:
      DISPLAY: unix$DISPLAY # Pass the display
    ports:
      - '8080:8080'
  jenkins:
    container_name: jenkins
    build: "jenkins/"
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS:-Djava.awt.headless=true
    volumes:
      - /var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
