pipeline{
    agent any
    stages {
        stage('Version') {
            steps {
                sh 'python3 --version'
            }
        }
        stage('Build') {
            steps {
                sh 'export DISPLAY="127.0.0.1:10.0" && xhost + && sudo apt-get install x11-xserver-utils && virtualenv && sudo venv && . venv/bin/activate && pip install -r requirements.txt && python src/menu.py'
            }
        }
    }
}
